# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.box_version = "201807.12.0"
  config.vm.hostname = 'trellis-dev'
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    set -e -x -u
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install gawk texinfo python-pip build-essential iptables automake autoconf libtool mininet isc-dhcp-server wireshark
    sudo pip install -U pip
    sudo pip install ipaddress
    git clone -b onos-1.11 https://gerrit.opencord.org/quagga
    cd quagga
    ./bootstrap.sh
    ./configure --enable-fpm --sbindir=/usr/lib/quagga enable_user=root enable_group=root
    make
    sudo make install
    cd ..

    sudo /etc/init.d/apparmor stop
    sudo ln -s /etc/apparmor.d/usr.sbin.dhcpd /etc/apparmor.d/disable/
    sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.dhcpd
    sudo sed -i '30i  /var/lib/dhcp{,3}/dhcpclient* lrw,' /etc/apparmor.d/sbin.dhclient
    sudo /etc/init.d/apparmor start

    git clone https://gerrit.onosproject.org/routing

    sudo ldconfig

    sudo ovs-vsctl set Open_vSwitch . other_config:vlan-limit=2
  SHELL

  config.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--cpus", 2]
      # enable this when you want to have more memory
      # v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ['modifyvm', :id, '--nicpromisc1', 'allow-all']
  end
end
